#!/usr/bin/env python

import argparse
from imgurscraper import scraper

parser = argparse.ArgumentParser()
parser.add_argument("client_id", help="imgur API client id")
parser.add_argument("url", help="URL of the imgur album to scrape")
parser.add_argument("path", help="path to save album images")
parser.add_argument("-v", "--verbose", help="increase output verbosity",
                    action="store_true")
args = parser.parse_args()

imgur_resource = scraper.prepare_url(args.client_id, args.url)
album_id = scraper.get_album_id(args.client_id, imgur_resource)
album_dir = scraper.mkdir_album(args.path, album_id)
scraper.scrape(args.client_id, album_id, album_dir, imgur_resource, args.verbose)
